### PR TITLE
fix: use getters for Models

### PR DESCRIPTION
**Pull request by L2jLiga**
*Issue:* #44, #45 

*Description of changes:*
Previous behaviour was to assign Model once per class which may produce mutations, now each class has own Model getter which returns new Object every time it called.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by dbanksdesign** [comment]
Thank you for your pull request. See my comment on #45 and we can discuss the best path forward. Thanks!

**Comment by dbanksdesign** [comment]
Looks like we are good to go with this!

**Comment by kgoedecke** [comment]
@L2jLiga would be great if you can resolve the conflicts :)

**Comment by L2jLiga** [comment]
Done

**Comment by L2jLiga** [comment]
Cool! %)

**Pull request merged**
