### PR TITLE
fix: remove empty textStyle object from Style

### PR DESCRIPTION
**Pull request by L2jLiga**
*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by jorgecasar** [comment]
Please @dbanksdesign can you merge this PR.

Sketch 69 crash or can't open files which contains LayerStyles with empty textStyle object.

**Review by dbanksdesign — APPROVED** [review]
LGTM! Sorry, been out for a bit. :shipit:

**Comment by jorgecasar** [comment]
Thanks!

**Pull request merged**
